// <auto-generated />
using System;
using Memorizer.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Memorizer.Data.Migrations
{
    [DbContext(typeof(MemoContext))]
    partial class memoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Memorizer.Data.Models.Memo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .IsUnicode(false);

                    b.Property<int>("PostponeLevel");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<DateTime>("RepeatDate");

                    b.Property<int>("Scores");

                    b.HasKey("Id");

                    b.HasIndex("Question")
                        .IsUnique()
                        .HasName("Q_Unique");

                    b.ToTable("Memos");
                });
#pragma warning restore 612, 618
        }
    }
}
